version: "3"
services:
  mongo:
    container_name: mongo-db-react
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME = 'secret-username'
      - MONGO_INITDB_ROOT_PASSWORD = 'secret-password'
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./mongo-volume:/data/db
